" An example for a vimrc file.
"
" Maintainer:	Bram Moolenaar <Bram@vim.org>
" Last change:	2019 Jan 26
"
" To use it, copy it to
"     for Unix and OS/2:  ~/.vimrc
"	      for Amiga:  s:.vimrc
"  for MS-DOS and Win32:  $VIM\_vimrc
"	    for OpenVMS:  sys$login:.vimrc

" When started as "evim", evim.vim will already have done these settings, bail
" out.
if v:progname =~? "evim"
  finish
endif

" Get the defaults that most users want.
source $VIMRUNTIME/defaults.vim

if has("vms")
  set nobackup		" do not keep a backup file, use versions instead
else
  set backup		" keep a backup file (restore to previous version)
  if has('persistent_undo')
    set undofile	" keep an undo file (undo changes after closing)
  endif
endif

if &t_Co > 2 || has("gui_running")
  " Switch on highlighting the last used search pattern.
  set hlsearch
endif

" Put these in an autocmd group, so that we can delete them easily.
augroup vimrcEx
  au!

  " For all text files set 'textwidth' to 78 characters.
  autocmd FileType text setlocal textwidth=78
augroup END

" Add optional packages.
"
" The matchit plugin makes the % command work better, but it is not backwards
" compatible.
" The ! means the package won't be loaded right away but when plugins are
" loaded during initialization.
if has('syntax') && has('eval')
  packadd! matchit
endif


" CUSTOM

filetype plugin indent on
syntax on

" Remap kj to esc
inoremap kj <Esc>
" In command mode, remap kj to ctrl+c, as esc for some vi compatibility
" reasons executes the command
cnoremap kj <C-C>

" Set utf-8 by default
set encoding=utf-8
set fileencoding=utf-8
set number

" Load plugins
call plug#begin('~/.vim/plugged')

" Latex plugin, that uses mupdf as default pdf viewer
Plug 'lervag/vimtex'
let g:vimtex_view_method='mupdf'
let g:tex_flavor='latex'
let g:vimtex_quickfix_mode=0
set conceallevel=1
let g:tex_conceal='abdmgs'

" Snippets pugin
Plug 'sirver/ultisnips'
let g:UtilSnipsExpandTrigger = '<tab>'
let g:UtilSnipsJumpForwardTrigger = '<tab>'
let g:UtilSnipsJumpBackwardTrigger = '<s-tab>'
let g:UltiSnipsSnippetsDir = '~/.vim/ultisnippets'
let g:UltiSnipsSnippetDirectories = ['ultisnippets']

call plug#end()


" Don't change appearance for concealed characters
hi! link Conceal Normal

" Correct spelling with Ctrl+L
setlocal spell
set spelllang=cs,en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u
